// @ts-nocheck — Legacy mock data, no longer used by the dashboard.
import { Building } from "./types";
import {
  calculateViabilityScore,
  estimateGallonsPerYear,
  estimateSavingsPerYear,
} from "./scoring";

interface BuildingSeed {
  id: string;
  name: string;
  address: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
  type: Building["type"];
  roof_area_sqft: number;
  cooling_tower_confidence: number;
  rainfall_inches: number;
  water_cost_index: number;
  esg_signal: Building["esg_signal"];
  stormwater_fee: boolean;
  tax_incentive: boolean;
  leed_certified: boolean;
}

const seeds: BuildingSeed[] = [
  {
    id: "bld-001",
    name: "Dallas Commerce Center",
    address: "2100 Commerce St",
    city: "Dallas",
    state: "TX",
    lat: 32.78,
    lng: -96.8,
    type: "commercial",
    roof_area_sqft: 185_000,
    cooling_tower_confidence: 92,
    rainfall_inches: 37,
    water_cost_index: 6,
    esg_signal: "strong",
    stormwater_fee: true,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-002",
    name: "Fort Worth Industrial Park",
    address: "4500 Industrial Blvd",
    city: "Fort Worth",
    state: "TX",
    lat: 32.75,
    lng: -97.33,
    type: "industrial",
    roof_area_sqft: 250_000,
    cooling_tower_confidence: 78,
    rainfall_inches: 34,
    water_cost_index: 5,
    esg_signal: "moderate",
    stormwater_fee: true,
    tax_incentive: false,
    leed_certified: false,
  },
  {
    id: "bld-003",
    name: "Austin Tech Campus",
    address: "1200 Research Blvd",
    city: "Austin",
    state: "TX",
    lat: 30.27,
    lng: -97.74,
    type: "data-center",
    roof_area_sqft: 120_000,
    cooling_tower_confidence: 95,
    rainfall_inches: 34,
    water_cost_index: 7,
    esg_signal: "strong",
    stormwater_fee: false,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-004",
    name: "Houston Logistics Hub",
    address: "8800 Port Houston Dr",
    city: "Houston",
    state: "TX",
    lat: 29.76,
    lng: -95.37,
    type: "warehouse",
    roof_area_sqft: 320_000,
    cooling_tower_confidence: 45,
    rainfall_inches: 50,
    water_cost_index: 5,
    esg_signal: "weak",
    stormwater_fee: true,
    tax_incentive: false,
    leed_certified: false,
  },
  {
    id: "bld-005",
    name: "Tucson Data Vault",
    address: "3300 Oracle Rd",
    city: "Tucson",
    state: "AZ",
    lat: 32.22,
    lng: -110.97,
    type: "data-center",
    roof_area_sqft: 95_000,
    cooling_tower_confidence: 88,
    rainfall_inches: 12,
    water_cost_index: 8,
    esg_signal: "strong",
    stormwater_fee: false,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-006",
    name: "Phoenix Distribution Center",
    address: "5500 W Buckeye Rd",
    city: "Phoenix",
    state: "AZ",
    lat: 33.45,
    lng: -112.07,
    type: "warehouse",
    roof_area_sqft: 210_000,
    cooling_tower_confidence: 62,
    rainfall_inches: 8,
    water_cost_index: 9,
    esg_signal: "moderate",
    stormwater_fee: false,
    tax_incentive: true,
    leed_certified: false,
  },
  {
    id: "bld-007",
    name: "Philadelphia Navy Yard Office",
    address: "1001 S Broad St",
    city: "Philadelphia",
    state: "PA",
    lat: 39.95,
    lng: -75.17,
    type: "commercial",
    roof_area_sqft: 145_000,
    cooling_tower_confidence: 85,
    rainfall_inches: 47,
    water_cost_index: 8,
    esg_signal: "strong",
    stormwater_fee: true,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-008",
    name: "Pittsburgh Steel Works",
    address: "200 River Ave",
    city: "Pittsburgh",
    state: "PA",
    lat: 40.44,
    lng: -80.0,
    type: "industrial",
    roof_area_sqft: 175_000,
    cooling_tower_confidence: 72,
    rainfall_inches: 38,
    water_cost_index: 7,
    esg_signal: "moderate",
    stormwater_fee: true,
    tax_incentive: false,
    leed_certified: false,
  },
  {
    id: "bld-009",
    name: "LA Fashion District Complex",
    address: "800 S Los Angeles St",
    city: "Los Angeles",
    state: "CA",
    lat: 34.05,
    lng: -118.24,
    type: "commercial",
    roof_area_sqft: 130_000,
    cooling_tower_confidence: 55,
    rainfall_inches: 15,
    water_cost_index: 9,
    esg_signal: "strong",
    stormwater_fee: true,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-010",
    name: "Sacramento Agri-Processing",
    address: "3400 Northgate Blvd",
    city: "Sacramento",
    state: "CA",
    lat: 38.58,
    lng: -121.49,
    type: "industrial",
    roof_area_sqft: 160_000,
    cooling_tower_confidence: 68,
    rainfall_inches: 20,
    water_cost_index: 8,
    esg_signal: "moderate",
    stormwater_fee: true,
    tax_incentive: true,
    leed_certified: false,
  },
  {
    id: "bld-011",
    name: "San Antonio Medical Campus",
    address: "7700 Floyd Curl Dr",
    city: "San Antonio",
    state: "TX",
    lat: 29.51,
    lng: -98.57,
    type: "commercial",
    roof_area_sqft: 110_000,
    cooling_tower_confidence: 90,
    rainfall_inches: 33,
    water_cost_index: 6,
    esg_signal: "strong",
    stormwater_fee: false,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-012",
    name: "Denver Tech Center",
    address: "4600 S Syracuse St",
    city: "Denver",
    state: "CO",
    lat: 39.74,
    lng: -104.99,
    type: "commercial",
    roof_area_sqft: 98_000,
    cooling_tower_confidence: 80,
    rainfall_inches: 17,
    water_cost_index: 7,
    esg_signal: "moderate",
    stormwater_fee: true,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-013",
    name: "Atlanta Peachtree Plaza",
    address: "191 Peachtree St NE",
    city: "Atlanta",
    state: "GA",
    lat: 33.76,
    lng: -84.39,
    type: "commercial",
    roof_area_sqft: 140_000,
    cooling_tower_confidence: 87,
    rainfall_inches: 50,
    water_cost_index: 6,
    esg_signal: "strong",
    stormwater_fee: true,
    tax_incentive: false,
    leed_certified: true,
  },
  {
    id: "bld-014",
    name: "Chicago Southside Warehouse",
    address: "3900 S Ashland Ave",
    city: "Chicago",
    state: "IL",
    lat: 41.88,
    lng: -87.63,
    type: "warehouse",
    roof_area_sqft: 280_000,
    cooling_tower_confidence: 40,
    rainfall_inches: 36,
    water_cost_index: 7,
    esg_signal: "weak",
    stormwater_fee: true,
    tax_incentive: false,
    leed_certified: false,
  },
  {
    id: "bld-015",
    name: "Orlando Convention Annex",
    address: "9800 International Dr",
    city: "Orlando",
    state: "FL",
    lat: 28.54,
    lng: -81.38,
    type: "commercial",
    roof_area_sqft: 200_000,
    cooling_tower_confidence: 75,
    rainfall_inches: 53,
    water_cost_index: 5,
    esg_signal: "moderate",
    stormwater_fee: false,
    tax_incentive: false,
    leed_certified: false,
  },
  {
    id: "bld-016",
    name: "Newark Industrial Complex",
    address: "150 Wilson Ave",
    city: "Newark",
    state: "NJ",
    lat: 40.74,
    lng: -74.17,
    type: "industrial",
    roof_area_sqft: 165_000,
    cooling_tower_confidence: 70,
    rainfall_inches: 46,
    water_cost_index: 9,
    esg_signal: "moderate",
    stormwater_fee: true,
    tax_incentive: true,
    leed_certified: false,
  },
  {
    id: "bld-017",
    name: "Seattle Cloud Campus",
    address: "2200 Westlake Ave",
    city: "Seattle",
    state: "WA",
    lat: 47.61,
    lng: -122.34,
    type: "data-center",
    roof_area_sqft: 88_000,
    cooling_tower_confidence: 93,
    rainfall_inches: 37,
    water_cost_index: 6,
    esg_signal: "strong",
    stormwater_fee: true,
    tax_incentive: true,
    leed_certified: true,
  },
  {
    id: "bld-018",
    name: "Miami Port Logistics",
    address: "1100 NW 20th St",
    city: "Miami",
    state: "FL",
    lat: 25.76,
    lng: -80.19,
    type: "warehouse",
    roof_area_sqft: 230_000,
    cooling_tower_confidence: 35,
    rainfall_inches: 62,
    water_cost_index: 6,
    esg_signal: "none",
    stormwater_fee: false,
    tax_incentive: false,
    leed_certified: false,
  },
];

function buildFromSeed(seed: BuildingSeed): Building {
  const gallons = estimateGallonsPerYear(seed.roof_area_sqft, seed.rainfall_inches);
  const savings = estimateSavingsPerYear(gallons, seed.water_cost_index);
  const viability = calculateViabilityScore(seed);

  return {
    ...seed,
    viability_score: viability,
    estimated_gallons_year: gallons,
    estimated_savings_year: savings,
  };
}

export const buildings: Building[] = seeds.map(buildFromSeed);

export const stateOptions = [
  { value: "ALL", label: "All States" },
  ...Array.from(new Set(seeds.map((s) => s.state)))
    .sort()
    .map((s) => ({ value: s, label: s })),
];
